name: Build the plugin

on:
  push:
    branches:
    - '**'
    tags-ignore:
    - '*'

jobs:
  build:

    runs-on: [windows-latest]

    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
    - uses: actions/checkout@v1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108

    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1

    - name: Build & package with `msbuild`
      run: |
        msbuild -target:restore -property:Configuration=Release
        msbuild -target:pack -property:Configuration=Release

    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ github.event.repository.name }}.nupkg
        path: src/${{ github.event.repository.name }}/bin/Release/${{ github.event.repository.name }}.0.0.0.nupkg
